pragma solidity 0.4.23;

import "CappedToken.sol";
import "PausableToken.sol";
import "StandardBurnableToken.sol";


/// @title ORSToken
/// @author Autogenerated from a Dia UML diagram
contract ORSToken is CappedToken, PausableToken, StandardBurnableToken {

    string public name = "ORS Token";
    string public symbol = "ORS";
    uint8 public decimals = 18;

    /// @dev Constructor
    /// @param _cap A positive number
    constructor(uint _cap) public CappedToken(_cap) {
        require(IMPLEMENTATION);
    }

}

